// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvOzt7dnHWPh_JY92BAMy0GuVe8G9Cr-Q',
    appId: '1:810469287590:web:928a93ccbd02dc7112f667',
    messagingSenderId: '810469287590',
    projectId: 'smartcomp-eaab4',
    authDomain: 'smartcomp-eaab4.firebaseapp.com',
    storageBucket: 'smartcomp-eaab4.firebasestorage.app',
    measurementId: 'G-9CMRG2HDWT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAv-IQtaPYZsrEpM4cQkju93tNv1R8k_rI',
    appId: '1:810469287590:android:f6a0c2a785237f7012f667',
    messagingSenderId: '810469287590',
    projectId: 'smartcomp-eaab4',
    storageBucket: 'smartcomp-eaab4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDI2VvHJoTfN-qTVnZXSnwUtXW3tmcpMdk',
    appId: '1:810469287590:ios:19b33a5ce096345c12f667',
    messagingSenderId: '810469287590',
    projectId: 'smartcomp-eaab4',
    storageBucket: 'smartcomp-eaab4.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplicationTubes2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDI2VvHJoTfN-qTVnZXSnwUtXW3tmcpMdk',
    appId: '1:810469287590:ios:19b33a5ce096345c12f667',
    messagingSenderId: '810469287590',
    projectId: 'smartcomp-eaab4',
    storageBucket: 'smartcomp-eaab4.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplicationTubes2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDvOzt7dnHWPh_JY92BAMy0GuVe8G9Cr-Q',
    appId: '1:810469287590:web:02e0b829f075e5ba12f667',
    messagingSenderId: '810469287590',
    projectId: 'smartcomp-eaab4',
    authDomain: 'smartcomp-eaab4.firebaseapp.com',
    storageBucket: 'smartcomp-eaab4.firebasestorage.app',
    measurementId: 'G-MWNHD6BERV',
  );
}
